/** Sugestões para o campo de aeroporto. Qualquer código IATA de 3 letras também funciona. */
export const AEROPORTOS: { codigo: string; nome: string }[] = [
  { codigo: "GRU", nome: "São Paulo – Guarulhos" },
  { codigo: "CGH", nome: "São Paulo – Congonhas" },
  { codigo: "VCP", nome: "Campinas – Viracopos" },
  { codigo: "GIG", nome: "Rio de Janeiro – Galeão" },
  { codigo: "SDU", nome: "Rio de Janeiro – Santos Dumont" },
  { codigo: "BSB", nome: "Brasília" },
  { codigo: "CNF", nome: "Belo Horizonte – Confins" },
  { codigo: "POA", nome: "Porto Alegre" },
  { codigo: "CWB", nome: "Curitiba" },
  { codigo: "FLN", nome: "Florianópolis" },
  { codigo: "SSA", nome: "Salvador" },
  { codigo: "REC", nome: "Recife" },
  { codigo: "FOR", nome: "Fortaleza" },
  { codigo: "NAT", nome: "Natal" },
  { codigo: "MCZ", nome: "Maceió" },
  { codigo: "BEL", nome: "Belém" },
  { codigo: "MAO", nome: "Manaus" },
  { codigo: "LIS", nome: "Lisboa" },
  { codigo: "OPO", nome: "Porto" },
  { codigo: "MAD", nome: "Madri" },
  { codigo: "BCN", nome: "Barcelona" },
  { codigo: "CDG", nome: "Paris – Charles de Gaulle" },
  { codigo: "LHR", nome: "Londres – Heathrow" },
  { codigo: "FCO", nome: "Roma – Fiumicino" },
  { codigo: "AMS", nome: "Amsterdã" },
  { codigo: "FRA", nome: "Frankfurt" },
  { codigo: "MIA", nome: "Miami" },
  { codigo: "MCO", nome: "Orlando" },
  { codigo: "JFK", nome: "Nova York – JFK" },
  { codigo: "EZE", nome: "Buenos Aires – Ezeiza" },
  { codigo: "SCL", nome: "Santiago" },
  { codigo: "LIM", nome: "Lima" },
  { codigo: "BOG", nome: "Bogotá" },
  { codigo: "PTY", nome: "Cidade do Panamá" },
  { codigo: "CUN", nome: "Cancún" },
  { codigo: "MVD", nome: "Montevidéu" },
];
